query Collections{
  collections{
    items{
      name
      slug
      position
      parentId
      parent{
        name
      }
      featuredAsset{
        name
        source
      }
    }
    totalItems
  }
}